name: Start_Minecraft_Bot

on:
  workflow_dispatch: # Das erlaubt es dir, den Bot per Knopf zu starten

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Installiere Library
        run: npm install mineflayer
      - name: Bot starten
        run: node bot.js
