name: Start_Minecraft_Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Installiere Libraries
        run: npm install mineflayer mineflayer-bedrock # Das fügt Bedrock-Support hinzu
      - name: Bot starten
        run: node bot.js
